stages:
    - build
    - release

variables:
  PACKAGE_REG_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/fpkg

#------------------#
#  Debug pipeline  #
#------------------#
.build-script:
    stage: build
    script:
        - startsection build "Build"
        - cargo build
        - endsection build

build-linux:
    stage: build
    except:
        - master
    image: "rust:latest"
    extends:
        - .build-script
    before_script:
        - . ./.gitlab/support/unix.sh

build-win64:
    stage: build
    except:
        - master
    tags:
        - windows
        - shared-windows
        - windows-1809
    before_script:
        - . ./.gitlab/support/windows.ps1
        - startsection deps "Install job dependencies"
        - choco install -y rust-ms
        - endsection deps
    extends:
        - .build-script

#------------------#
# Release pipeline #
#------------------#
get-version:
    stage: build
    image: debian:stable
    only:
        - master
    script:
        # Part 1 > extract the version line
        # Part 2 > extract the version string itself
        # Part 3 > remove colors
        - grep -P 'version = "\d.\d.\d"' core/Cargo.toml | grep -oP '\d.\d.\d' | cat > core/versionfile.txt
        - grep -P 'version = "\d.\d.\d"' codegen/Cargo.toml | grep -oP '\d.\d.\d' | cat > codegen/versionfile.txt
    artifacts:
        paths:
            - core/versionfile.txt
            - codegen/versionfile.txt

build-release:
    stage: build
    image: "rust:latest"
    only:
        - master
    before_script:
        - . ./.gitlab/support/unix.sh
    script:
        - startsection build "Build release"
        - cargo build --release
        - endsection build

publish:
    stage: release
    image: "registry.gitlab.com/torkleyy/cargo-publish-all:latest"
    only:
        - master
    before_script:
        - . ./.gitlab/support/unix.sh
    script:
        - startsection build "Push to crates.io"
        - cargo-publish-all --token ${RELEASE_TOKEN} --yes
        - endsection build

create-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - get-version
  only:
    - master
  script:
    - PACKAGE_VERSION=$(cat core/versionfile.txt)
    - CODEGEN_VERSION=$(cat codegen/versionfile.txt)
    - echo "Creating release v${PACKAGE_VERSION}..."
    - |
      release-cli create --name "Rust Extended Generic ECS (core ${PACKAGE_VERSION}, codegen ${CODEGEN_VERSION})" --tag-name "${PACKAGE_VERSION}-${CODEGEN_VERSION}" \
        --assets-link "{\"name\":\"Crates.io release\",\"url\":\"https://crates.io/crates/regecs\"}" \
        --assets-link "{\"name\":\"Codegen Crates.io release\",\"url\":\"https://crates.io/crates/regecs-codegen\"}" \
